POST http://127.0.0.1:8083/auth
Content-Type: application/json

{
    "username": "79035972452",
    "password": "96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e"
}
{{
    exports.TOKEN = response.parsedBody.access_token;
}}

###
GET http://127.0.0.1:8083/user/id/6450fe088d29d0caa8521886
Authorization: JWT {{TOKEN}}


PUT http://127.0.0.1:8083/user
Authorization: JWT {{TOKEN}}
Content-Type: application/json

{
    "login": "login",
    "password": "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
    "something": "here"
}


PUT http://127.0.0.1:8083/user/register
Authorization: JWT {{TOKEN}}
Content-Type: application/json

{
    "password": "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8",
    "login": "testtest"
}


PUT http://127.0.0.1:8083/user/register/645a7dcabee285f93cbf0f8f/sendcode
Authorization: JWT {{TOKEN}}
Content-Type: application/json

{
    "_id": "645a7dcabee285f93cbf0f8f",
    "password": "96cae35ce8a9b0244178bf28e4966c2ce1b8385723a96a6b838858cdd6ca0a1e",
    "login": "79035972452"
}


PUT http://127.0.0.1:8083/user/register/6454dd3a93e2f50ba7096c92/checkcode
Authorization: JWT {{TOKEN}}
Content-Type: application/json

{
    "login": "testtest",
    "smscode": "2779"
}


PUT http://127.0.0.1:8083/user/6450fe088d29d0caa8521886
Authorization: JWT {{TOKEN}}
Content-Type: application/json

{
    "phone": "this is phone"
}
